### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by jjoseph-le** [GoatPad-cs270/LLGSHH-Pad#10]

**Comment by kcaldarone** [comment]
Printing should be easily accessible with either a dropdown menu or a CTRL + P key bind in order to open up a pop-up and let us print the contents of the desired file.

How we could do it: Use java swing with a CTRL+P key bind to open up a JPanel. From there, you can print out your desired file.

**Comment by jjoseph-le** [comment]
Application needs the functionality to print any given GoatPad input. Pressing CTRL P will open a popup window with a print preview of the GoatPad. Options might include destination (i.e dropdowns of multiple printers, different save options), print certain pages, and paper layout.
