### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by sboutros22** [GoatPad-cs270/LLGSHH-Pad#2]
The interface probably is the most important feature of the project and one that we would need to complete early on. That is because everything that is going to be done needs a place to do it on. It needs to be able to write and edit text, save and edit and so on.
Here a few examples.
#6 #4 #10

**Comment by jcraven24** [comment]
window, dropdown boxes, and toolbar classes made with beginnings of methods.

**Comment by erikyz** [comment]
#5 
#8 
#10 
#12 
All listed above are interface issues in progress.
