### ISSUE TITLE
Clipboard functions; Copy/paste, cut, undo/redo, etc.

### ISSUE THREAD

**Issue by jjoseph-le** [GoatPad-cs270/LLGSHH-Pad#4]
The application needs some tools to help with writing and fixing contents of texts. The copy/ paste and cut are useful in moving large text from different parts of the page to help remove the need for re-writing the same text over and over again. The Undo/ redo feature is needed incase mistakes were made and the person just wants a quick fix the issue without to much hassle. Other features that could be includes all serve a similar function in trying to make working in the text or with the text simpler and faster.

**Comment by jcraven24** [comment]
Action class made to handle the queue of actions recently made to the document to be undone/redone
also can access clipboard now
