### ISSUE TITLE
Drop down menu on Text Editor

### ISSUE THREAD

**Issue by jjoseph-le** [GoatPad-cs270/LLGSHH-Pad#5]

**Comment by kcaldarone** [comment]
The drop down menu for this software should be put at the top left of the text editor window and you should be able to click it to drop down a menu containing the following, Print (#10 ), Open/Save Files (#6 ), and more we can add in the future

How we could do it: Have a button through Java Swing on the text editor on the top left where if we click it, a drop down menu appears and has other buttons for the options stated above in the description.

**Comment by erikyz** [comment]
Set up frame for dropdown menu. Drop down menu appears in popup window.

**Comment by erikyz** [comment]
setup dropdown into a panel, placed that panel into a frame.

**Comment by erikyz** [comment]
Set up event listener that functions with combobox in preparation for corresponding functions.
