### ISSUE TITLE
Save/Open .txt Files

### ISSUE THREAD

**Issue by jjoseph-le** [GoatPad-cs270/LLGSHH-Pad#6]

**Comment by jcraven24** [comment]
The application is able to open a text file (.txt) from the computer/digital storage to edit (max of 512MB). 
Also allows the user to save the text file (.txt) to the desired storage location.

Make sure that when saving the text file it goes to the correct location and nothing is lost. When opening, make sure it can open up to 512MB and successfully open the file without losing or corrupting data.

**Comment by jcraven24** [comment]
basic access to files and file paths, tests to make sure correctly opens
